### ISSUE TITLE
Base64 is not defined in Node.js environment

### ISSUE THREAD

**Issue by CocaCola183** [tcorral/JSONC#7]
`JSONC.js:275`

```js
return Base64.encode(String.fromCharCode.apply(String, gzip.zip(str,{level:9})));
```

**Comment by CocaCola183** [comment]
may be `gzip` is not defined too

**Comment by sd031** [comment]
I am getting this issue too in node.js

**Comment by ehartford** [comment]
Same here.

    /Users/hartbeat/node_modules/jsoncomp/src/JSONC.js:275
        return Base64.encode(String.fromCharCode.apply(String, gzip.zip(str,{level:9})));
               ^

    ReferenceError: Base64 is not defined
        at Object.JSONC.pack (/Users/hartbeat/node_modules/jsoncomp/src/JSONC.js:275:12)
        at Object.<anonymous> (/Users/hartbeat/scratch/thing.js:94:33)

**Comment by muthmano-dev** [comment]
Any workaround for this ?

**Comment by shreychaturvedi123** [comment]
any update on this issue?

**Comment by roschler** [comment]
Hey everyone, it's a little hard to find but you can find it here:

http://www.webtoolkit.info/javascript_base64.html#.Wuy0KXXwbCJ

**Comment by jamesearl** [comment]
Or you can do something like this, before you try to call a function that depends on these:

```js
global.Base64 = {
  encode: function(str) {
    return Buffer.from(str).toString('base64');
  },
};
global.gzip = {
  zip: function(str) {
    return zlib.gzipSync(Buffer.from(str));
  },
}
```

Hacky but it gets the job done.
